// NewPostForm exercises the full read+write loop:
//   - useCreatePost (mutation) hits POST /api/posts via MSW
//   - The optimistic update writes to the queryClient cache
//   - On success, the form resets
//   - On 500, the form shows the error and keeps the values
//
// Tests use renderWithProviders to install a fresh QueryClient per test.

import { describe, it, expect } from 'vitest';
import { screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { http, HttpResponse } from 'msw';
import { renderWithProviders } from '../test/renderWithProviders.jsx';
import { server } from '../test/setup.js';
import NewPostForm from './NewPostForm.jsx';

describe('NewPostForm', () => {
  it('disables the submit button when the body is empty', () => {
    renderWithProviders(<NewPostForm />, { withRouter: false });
    expect(screen.getByRole('button', { name: /post/i })).toBeDisabled();
  });

  it('enables the submit button as soon as the body has text', async () => {
    const user = userEvent.setup();
    renderWithProviders(<NewPostForm />, { withRouter: false });

    await user.type(screen.getByPlaceholderText(/what's on your mind/i), 'hi');
    expect(screen.getByRole('button', { name: /post/i })).toBeEnabled();
  });

  it('clears the inputs after a successful submit', async () => {
    const user = userEvent.setup();
    renderWithProviders(<NewPostForm />, { withRouter: false });

    const title = screen.getByPlaceholderText(/title/i);
    const body = screen.getByPlaceholderText(/what's on your mind/i);
    await user.type(title, 'A title');
    await user.type(body, 'Some body');
    await user.click(screen.getByRole('button', { name: /post/i }));

    // After the mutation settles, the inputs reset.
    expect(await screen.findByPlaceholderText(/title/i)).toHaveValue('');
    expect(screen.getByPlaceholderText(/what's on your mind/i)).toHaveValue('');
  });

  it('surfaces a server error and keeps the user input', async () => {
    server.use(
      http.post('/api/posts', () =>
        HttpResponse.json({ message: 'Boom' }, { status: 500 })
      )
    );

    const user = userEvent.setup();
    renderWithProviders(<NewPostForm />, { withRouter: false });

    await user.type(screen.getByPlaceholderText(/title/i), 'Will fail');
    await user.type(screen.getByPlaceholderText(/what's on your mind/i), 'failtext');
    await user.click(screen.getByRole('button', { name: /post/i }));

    // Error message visible to the user.
    expect(await screen.findByRole('alert')).toHaveTextContent(/couldn't post/i);
    // User's input preserved (so they don't lose what they typed).
    expect(screen.getByPlaceholderText(/title/i)).toHaveValue('Will fail');
    expect(screen.getByPlaceholderText(/what's on your mind/i)).toHaveValue('failtext');
  });

  // ---------------------------------------------------------------------
  // Below this line: tests originally generated by an AI, then reviewed
  // and either kept, refactored, or deleted per lab07-review.md.
  // ---------------------------------------------------------------------

  it('shows "Posting…" while the mutation is in flight', async () => {
    // Slow handler so we can observe the pending state.
    server.use(
      http.post('/api/posts', async () => {
        await new Promise((r) => setTimeout(r, 50));
        return HttpResponse.json(
          {
            id: 'x',
            title: '',
            body: 'slow',
            author: 'test@example.com',
            createdAt: new Date().toISOString(),
          },
          { status: 201 }
        );
      })
    );
    const user = userEvent.setup();
    renderWithProviders(<NewPostForm />, { withRouter: false });

    await user.type(screen.getByPlaceholderText(/what's on your mind/i), 'slow');
    await user.click(screen.getByRole('button', { name: /post/i }));

    expect(
      await screen.findByRole('button', { name: /posting…/i })
    ).toBeDisabled();
  });

  it('does not submit when the body is whitespace-only', async () => {
    let postCount = 0;
    server.use(
      http.post('/api/posts', () => {
        postCount++;
        return HttpResponse.json({ id: 'x' }, { status: 201 });
      })
    );
    const user = userEvent.setup();
    renderWithProviders(<NewPostForm />, { withRouter: false });

    await user.type(screen.getByPlaceholderText(/what's on your mind/i), '   ');
    // Button stays disabled when the trimmed body is empty.
    expect(screen.getByRole('button', { name: /post/i })).toBeDisabled();
    expect(postCount).toBe(0);
  });
});
